name: default
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install --global yarn
      - run: yarn set version berry
      - run: yarn install
      - run: yarn test
